version: '3'

services:
  home-page:
    image: nginx
    container_name: home-page
    restart: unless-stopped
    ports:
      - 8080:80
    build: .
    environment:
      - APP_PORT=8080
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - nginx-proxy_net
networks:
  nginx-proxy_net:
    external: true