version: '3.8'

services:
  home-page:
    image: jwilder/whoami
    container_name: home-page
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      VIRTUAL_PORT: 8081
      NGINX_PORT: 8081
    external_links:
      - nginx-router
    volumes:
      - ./public:/usr/share/nginx/html/
    networks:
      - rt_ssl_proxy_default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=home-page"
      - "traefik.frontend.rule=Host:reckless.technology"  
  #      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
      - "traefik.port=8081"
      - "traefik.docker.network=rt_ssl_proxy_default"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=reckless.technology"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
  #      - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:reckless.technology"
    
networks:
  rt_ssl_proxy_default:
    external: true