version: '3'

services:
  home-page:
    image: nginx
    container_name: home-page
    restart: unless-stopped
    ports:
      - 8080:80
    build:
      context: .
      args:
        - VIRTUAL_PORT=${{VIRTUAL_PORT}}
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    external: true