version: '3.3'

services:
  home-page:
    image: nginx:latest

    container_name: home-page

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/home/node/app:rw
      - data_dir:/etc/nginx/:rw
    build: .
    networks:
      - traefik-proxy
    ports:
      - 8081:80

    environment:
      - "APP_PORT=8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-page.rule=Host(`reckless.technology`) && PathPrefix(`/`)"
      - "traefik.http.routers.home-page.tls.certresolver=letsEncrypt"
    restart: unless-stopped
volumes:
  app_dir:
  extensions_dir:
  data_dir:
networks:
  traefik-proxy:
    external: true