version: '3.8'

services:
  home-page:
    image: nginx:latest
    container_name: home-page
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      LETSENCRYPT_HOST: reckless.technology/
      VIRTUAL_HOST: reckless.technology/
      VIRTUAL_PORT: 8080
      NGINX_HOST: reckless.technology/
      NGINX_PORT: 8080
    build: .
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    external: true
volumes:
  html: