version: '3.3'

services:
  home-page:
    image: nginx:latest
    container_name: home-page
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./public:/usr/share/nginx/html/
    networks:
      - traefik-proxy
    labels:
      - "traefik.http.routers.router0.rule=Host(`reckless.technology`) && PathPrefix(`/`)"
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsEncrypt
      - traefik.http.routers.whoami.service=home-page
      - traefik.http.services.whoami.loadbalancer.server.port=8081
networks:
  traefik-proxy:
    external: true