version: '3'

services:
  nginx:
    image: nginx:alpine
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=reckless.technology
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=reckless.technology
      - LETSENCRYPT_EMAIL=travis@travisbennett.com
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy