on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Build the docker-compose stack
      run: docker-compose build --no-cache
    - name: Deploy the docker-compose stack
      run: docker-compose --verbose -f docker-compose.yml up --force-recreate -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker-compose logs